thecut/catalogue/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import include, patterns, url
from thecut.catalogue.views import attribute, brand, category, product, sku


urls = patterns(
    'thecut.catalogue.views',

    url(r'^categories/$',
        category.ListView.as_view(), name='category_list'),
    url(r'^categories/(?P<page>\d+)$',
        category.ListView.as_view(), name='paginated_category_list'),
    url(r'^category/(?P<slug>[\w-]+)$',
        category.DetailView.as_view(), name='category_detail'),

    url(r'^category/(?P<slug>[\w-]+)/products$',
        product.CategoryListView.as_view(), name='product_category_list'),
    url(r'^category/(?P<slug>[\w-]+)/products/(?P<page>\d+)$',
        product.CategoryListView.as_view(),
        name='paginated_product_category_list'),

    url(r'^brand/(?P<slug>[\w-]+)/products$',
        product.BrandListView.as_view(), name='product_brand_list'),
    url(r'^brand/(?P<slug>[\w-]+)/products/(?P<page>\d+)$',
        product.BrandListView.as_view(), name='paginated_product_brand_list'),

    url(r'^brands/$',
        brand.ListView.as_view(), name='brand_list'),
    url(r'^brands/(?P<page>\d+)$',
        brand.ListView.as_view(), name='paginated_brand_list'),
    url(r'^brand/(?P<slug>[\w-]+)$',
        brand.DetailView.as_view(), name='brand_detail'),

    url(r'^products/$',
        product.ListView.as_view(), name='product_list'),
    url(r'^products/(?P<page>\d+)$',
        product.ListView.as_view(), name='paginated_product_list'),
    url(r'^product/(?P<slug>[\w-]+)$',
        product.DetailView.as_view(), name='product_detail'),

    url(r'^skus/$',
        sku.ListView.as_view(), name='sku_list'),
    url(r'^skus/(?P<page>\d+)$',
        sku.ListView.as_view(), name='paginated_sku_list'),
    url(r'^sku/(?P<pk>\d+)$',
        sku.DetailView.as_view(), name='sku_detail'),

    url(r'^attributes/$',
        attribute.ListView.as_view(), name='attribute_list'),
    url(r'^attributes/(?P<page>\d+)$',
        attribute.ListView.as_view(), name='paginated_attribute_list'),
    url(r'^attributes/(?P<pk>\d+)$',
        attribute.DetailView.as_view(), name='attribute_detail'),
)

urlpatterns = patterns(
    '', (r'^', include(urls, namespace='catalogue')),
)

thecut/catalogue/templates/catalogue/_product_list.html
{# Is used to render list of products. #}
{# Gets: list of products in product_list. #}

{% for product in product_list %}
  {% if forloop.first %}
    <table>
      <thead>
        <tr>
          <th>Title</th>
          <th>Brand</th>
        </tr>
      </thead>
      <tbody>
  {% endif %}
  <tr>
    <td><a href="{{ product.get_absolute_url }}">
      {{ product.title }}
    </a></td><td>
      {{ product.brand|default:"" }}
    </td>
  </tr>
  {% if forloop.last %}
    </tbody></table>
  {% endif %}
{% empty %}
  <p>No products to display.</p>
{% endfor %}

thecut/catalogue/templates/catalogue/_sku_list.html
{# Is used to render list of SKUs. #}
{# Gets: list of SKUs in sku_list. #}

{% for sku in sku_list %}
  {% if forloop.first %}
    <table>
      <thead>
        <tr>
          <th>Product</th>
          <th>Attributes</th>
          <th>SKU code</th>
        </tr>
      </thead>
      <tbody>
  {% endif %}
  <tr>
    <td><a href="{{ sku.get_absolute_url }}">
      {{ sku.product.title }}
    </a></td><td>
      {{ sku.attributes_description }}
    </td><td>
      {{ sku.sku }}
    </td>
  </tr>
  {% if forloop.last %}
    </tbody></table>
  {% endif %}
{% empty %}
  <p>No items to display.</p>
{% endfor %}

thecut/catalogue/templates/catalogue/attribute_detail.html
{% extends "catalogue/base.html" %}

{% block title %}{{ attribute.name }} - {{ block.super }}{% endblock %}

{% block content %}
  <header>
    <h1>{{ attribute.name }}</h1>
    {% if attribute.is_removed %}
      <h4>This attribute has been removed.</h4>
    {% endif %}
<div>{% block top_actions %}{% endblock %}</div>

  </header>
  <section class="main-content">
    <ul class="actions">
      <li>
        <a href="{% url "catalogue:attribute_list" %}" class="back">
          &larr; Back to all Attributes list
        </a>
      </li>
    </ul>
  </section>

{% endblock %}

thecut/catalogue/templates/catalogue/attribute_list.html
{% extends "catalogue/base.html" %}
{% load url from future %}

{% block title %}Attributes - {{ block.super }}{% endblock %}

{% block extrahead %}
  {{ block.super }}
  {% if page_obj.paginator.num_pages > 1 %}
    {% if page_obj.has_previous %}
      {% if page_obj.previous_page_number == 1 %}
        <link rel="prev"
              href="{% url "catalogue:attribute_list" %}" />
      {% else %}
        <link rel="prev"
              href="{% url "catalogue:paginated_attribute_list" page=page_obj.previous_page_number %}" />
      {% endif %}
    {% endif %}
    {% if page_obj.has_next %}
      <link rel="next"
            href="{% url "catalogue:paginated_attribute_list" page=page_obj.next_page_number %}"/>
    {% endif %}
  {% endif %}
{% endblock %}

{% block content %}
  <header><h1>Attributes</h1></header>

  <section class="main-content">
    <section class="content">
{% block above_list_actions %}{% endblock %}
      <section class="list">
        {% for attribute in attribute_list %}
          {% if forloop.first %}
            <table>
              <thead>
                <tr><th>Name</th></tr>
              </thead>
              <tbody>
          {% endif %}
          <tr>
            <td><a href="{{ attribute.get_absolute_url }}">
              {{ attribute.name }}
            </a></td>
          </tr>
          {% if forloop.last %}
            </tbody></table>
          {% endif %}
        {% empty %}
          <p>No brands to display.</p>
        {% endfor %}

        {% if page_obj.paginator.num_pages > 1 %}
          <div>
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.

            {% if page_obj.has_previous %}
              {% if page_obj.previous_page_number == 1 %}
                <a href="{% url "catalogue:attribute_list" %}"
              {% else %}
                <a href="{% url "catalogue:paginated_attribute_list" page=page_obj.previous_page_number %}"
              {% endif %}
                   rel="previous">previous</a>
            {% endif %}

            {% if page_obj.has_next %}
              <a href="{% url "catalogue:paginated_attribute_list" page_obj.next_page_number %}"
                 rel="next">next</a>
            {% endif %}

          </div>
        {% endif %}
      </section>
    </section>
  </section>
{% endblock %}

thecut/catalogue/templates/catalogue/base.html
{% extends "base.html" %}

thecut/catalogue/templates/catalogue/brand_detail.html
{% extends "catalogue/base.html" %}

{% block title %}{{ brand.title }} - {{ block.super }}{% endblock %}

{% block content %}
  <header>
    <h1>{{ brand.title }}</h1>
    {% if brand.is_removed %}
      <h4>This brand has been removed.</h4>
    {% endif %}
<div>{% block top_actions %}{% endblock %}</div>
  </header>
  <section class="main-content">
  <section class="content">
    {% for product in brand.products.not_removed %}
    {% if forloop.first %}
      <h3>Products</h3>
      <section class="list">
        <ul>
    {% endif %}
          <li>
            <a href="{{ product.get_absolute_url }}">{{ product }}</a>
          </li>
    {% if forloop.last %}
        </ul>
      </section>
    {% endif %}
  {% endfor %}

  <ul>
    <li>
      <a href="{% url "catalogue:brand_list" %}" class="back">
        &larr; All Brands
      </a>
    </li>
  </ul>
  </section>
  </section>

{% endblock %}

thecut/catalogue/templates/catalogue/brand_list.html
{% extends "catalogue/base.html" %}
{% load url from future %}

{% block title %}Brands - {{ block.super }}{% endblock %}

{% block extrahead %}
  {{ block.super }}
  {% if page_obj.paginator.num_pages > 1 %}
    {% if page_obj.has_previous %}
      {% if page_obj.previous_page_number == 1 %}
        <link rel="prev"
              href="{% url "catalogue:brand_list" %}" />
      {% else %}
        <link rel="prev"
              href="{% url "catalogue:paginated_brand_list" page=page_obj.previous_page_number %}" />
      {% endif %}
    {% endif %}
    {% if page_obj.has_next %}
      <link rel="next"
            href="{% url "catalogue:paginated_brand_list" page=page_obj.next_page_number %}"/>
    {% endif %}
  {% endif %}
{% endblock %}

{% block content %}
  <header><h1>Brands</h1></header>

  <section class="main-content">
    <section class="content">
{% block above_list_actions %}{% endblock %}
      <section class="list">
        {% for brand in brand_list %}
          {% if forloop.first %}
            <table>
              <thead>
                <tr><th>Title</th></tr>
              </thead>
              <tbody>
          {% endif %}
          <tr>
            <td><a href="{{ brand.get_absolute_url }}">
              {{ brand.title }}
            </a></td>
          </tr>
          {% if forloop.last %}
            </tbody></table>
          {% endif %}
        {% empty %}
          <p>No brands to display.</p>
        {% endfor %}

        {% if page_obj.paginator.num_pages > 1 %}
          <div>
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.

            {% if page_obj.has_previous %}
              {% if page_obj.previous_page_number == 1 %}
                <a href="{% url "catalogue:brand_list" %}"
              {% else %}
                <a href="{% url "catalogue:paginated_brand_list" page=page_obj.previous_page_number %}"
              {% endif %}
                   rel="previous">previous</a>
            {% endif %}

            {% if page_obj.has_next %}
              <a href="{% url "catalogue:paginated_brand_list" page_obj.next_page_number %}"
                 rel="next">next</a>
            {% endif %}

          </div>
        {% endif %}
      </section>
    </section>
  </section>
{% endblock %}

thecut/catalogue/templates/catalogue/category_detail.html
{% extends "catalogue/base.html" %}

{% block title %}{{ category.title }} - {{ block.super }}{% endblock %}

{% block content %}
  <header>
    <h1>{{ category.title }}</h1>
    {% if brand.is_removed %}
      <h4>This category has been removed.</h4>
    {% endif %}
<div>{% block top_actions %}{% endblock %}</div>

  </header>
  <section class="main-content">
  <section class="content">
    {% for product in category.products.not_removed %}
    {% if forloop.first %}
      <h3>Products</h3>
      <section class="list">

        <ul>
    {% endif %}
          <li>
            <a href="{{ product.get_absolute_url }}">{{ product }}</a>
          </li>
    {% if forloop.last %}
        </ul>
      </section>
    {% endif %}
  {% endfor %}

    <ul class="actions">
      <li>
        <a href="{% url "catalogue:category_list" %}" class="back">
          &larr; All Categories
        </a>
      </li>
    </ul>
  </section>
  </section>

{% endblock %}

thecut/catalogue/templates/catalogue/category_list.html
{# Is used to render list of categories. #}
{# Has above_list_actions block to insert "Add category" button. #}


{% extends "catalogue/base.html" %}
{% load url from future %}

{% block title %}Categories - {{ block.super }}{% endblock %}

{% block extrahead %}
  {{ block.super }}

  {% if page_obj.paginator.num_pages > 1 %}
    {% if page_obj.has_previous %}
      <link rel="prev"
        {% if page_obj.previous_page_number == 1 %}
            href="{% url "catalogue:category_list" %}"/>
        {% else %}
            href="{% url "catalogue:paginated_category_list" page=page_obj.previous_page_number %}"/>
        {% endif %}
    {% endif %}
    {% if page_obj.has_next %}
      <link rel="next"
            href="{% url "catalogue:paginated_category_list" page=page_obj.next_page_number %}"/>
    {% endif %}
  {% endif %}
{% endblock %}

{% block content %}
  <header><h1>Categories</h1></header>

  <section class="main-content">
    <section class="content">
{% block above_list_actions %}{% endblock %}
      <section class="list">

        {% for category in category_list %}
          {% if forloop.first %}
            <table>
              <thead>
                <tr><th>Title</th></tr>
              </thead>
              <tbody>
          {% endif %}
          <tr>
            <td><a href="{{ category.get_absolute_url }}">
              {{ category.title }}
            </a></td>
          </tr>
          {% if forloop.last %}
            </tbody></table>
          {% endif %}
        {% empty %}
          <p>No categories to display.</p>
        {% endfor %}

        {% if page_obj.paginator.num_pages > 1 %}
          <div>
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.

            {% if page_obj.has_previous %}
              {% if page_obj.previous_page_number == 1 %}
                <a href="{% url "catalogue:category_list" %}"
              {% else %}
                <a href="{% url "catalogue:paginated_category_list" page=page_obj.previous_page_number %}"
              {% endif %}
                 rel="previous">previous</a>
            {% endif %}

            {% if page_obj.has_next %}
              <a href="{% url "catalogue:paginated_category_list" page_obj.next_page_number %}"
                 rel="next">next</a>
            {% endif %}

          </div>
        {% endif %}
      </section>
    </section>
  </section>
{% endblock %}

thecut/catalogue/templates/catalogue/product_brand_list.html
{# Is used to render list of products of one brand. #}
{# Has above_list_actions block to insert "Add product" button. #}

{% extends "catalogue/base.html" %}
{% load url from future %}

{% block title %}{{ brand.title }} - {{ block.super }}{% endblock %}

{% block extrahead %}
  {{ block.super }}
  {% if page_obj.paginator.num_pages > 1 %}
    {% if page_obj.has_previous %}
      {% if page_obj.previous_page_number == 1 %}
        <link rel="prev"
              href="{% url "catalogue:product_brand_list" slug=brand.slug %}" />
      {% else %}
        <link rel="prev"
              href="{% url "catalogue:paginated_product_brand_list" page=page_obj.previous_page_number slug=brand.slug %}" />
      {% endif %}
    {% endif %}
    {% if page_obj.has_next %}
      <link rel="next"
            href="{% url "catalogue:paginated_product_brand_list" page=page_obj.next_page_number slug=brand.slug %}"/>
    {% endif %}
  {% endif %}
{% endblock %}

{% block content %}
  <header>
    <h1>{{ brand.title }}</h1>
    <a href="{% url "catalogue:brand_list" %}">Back to all Brands</a>
  </header>

  <section class="main-content">
    <section class="content">
{% block above_list_actions %}{% endblock %}
      <section class="list">

        {% include "catalogue/_product_list.html" with product_list=product_list %}

        {% if page_obj.paginator.num_pages > 1 %}
          <div>
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.

            {% if page_obj.has_previous %}
              {% if page_obj.previous_page_number == 1 %}
                <a href="{% url "catalogue:product_brand_list" slug=brand.slug %}"
              {% else %}
                <a href="{% url "catalogue:paginated_product_brand_list" page=page_obj.previous_page_number slug=brand.slug %}"
              {% endif %}
                   rel="previous">previous</a>
            {% endif %}

            {% if page_obj.has_next %}
              <a href="{% url "catalogue:paginated_product_brand_list" page=page_obj.next_page_number slug=brand.slug %}"
                 rel="next">next</a>
            {% endif %}

          </div>
        {% endif %}
      </section>
    </section>
  </section>
{% endblock %}

thecut/catalogue/templates/catalogue/product_category_list.html
{# Is used to render list of products of one category. #}
{# Has above_list_actions block to insert "Add product" button. #}

{% extends "catalogue/base.html" %}
{% load url from future %}

{% block title %}{{ category.title }} - {{ block.super }}{% endblock %}

{% block extrahead %}
  {{ block.super }}
  {% if page_obj.paginator.num_pages > 1 %}
    {% if page_obj.has_previous %}
      {% if page_obj.previous_page_number == 1 %}
        <link rel="prev"
              href="{% url "catalogue:product_category_list" slug=category.slug %}" />
      {% else %}
        <link rel="prev"
              href="{% url "catalogue:paginated_product_category_list" page=page_obj.previous_page_number slug=category.slug %}" />
      {% endif %}
    {% endif %}
    {% if page_obj.has_next %}
      <link rel="next"
            href="{% url "catalogue:paginated_product_category_list" page=page_obj.next_page_number slug=category.slug %}"/>
    {% endif %}
  {% endif %}
{% endblock %}

{% block content %}
  <header>
    <h1>{{ category.title }}</h1>
    <a href="{% url "catalogue:category_list" %}">Back to all Categories</a>
  </header>

  <section class="main-content">
    <section class="content">
{% block above_list_actions %}{% endblock %}
      <section class="list">

        {% include "catalogue/_product_list.html" with product_list=product_list %}

        {% if page_obj.paginator.num_pages > 1 %}
          <div>
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.

            {% if page_obj.has_previous %}
              {% if page_obj.previous_page_number == 1 %}
                <a href="{% url "catalogue:product_category_list" slug=category.slug %}"
              {% else %}
                <a href="{% url "catalogue:paginated_product_category_list" page=page_obj.previous_page_number slug=category.slug %}"
              {% endif %}
                   rel="previous">previous</a>
            {% endif %}

            {% if page_obj.has_next %}
              <a href="{% url "catalogue:paginated_product_category_list" page=page_obj.next_page_number slug=category.slug %}"
                 rel="next">next</a>
            {% endif %}

          </div>
        {% endif %}
      </section>
    </section>
  </section>
{% endblock %}

thecut/catalogue/templates/catalogue/product_detail.html
{% extends "catalogue/base.html" %}

{% block title %}{{ product.title }} - {{ block.super }}{% endblock %}

{% block content %}
  <header>
    <h1>{{ product.title }}</h1>
    {% if product.is_removed %}
      <h4>This product has been removed.</h4>
    {% endif %}
<div>{% block top_actions %}{% endblock %}</div>
  </header>
<section class="main-content"><section class="content">
  <h3>Product details</h3>

  <section class="list">
    <ul>
      {% if product.brand %}
        <li>Brand:
          <a href="{% url "catalogue:brand_detail" slug=product.brand.slug %}">
            {{ product.brand }}
          </a>
        </li>
      {% endif %}
      {% if product.primary_category %}
        <li>Primary Category:
          <a href="{% url "catalogue:category_detail" slug=product.primary_category.slug %}">
            {{ product.primary_category }}
          </a>
        </li>
      {% endif %}
    </ul>
  </section>
  {% if product.primary_category %}
    <h3>Categories</h3>
    <section class="list">
    <ul>
      {% for category in product.categories.all %}
        <li><a href="{{ category.get_absolute_url }}">{{ category }}</a></li>
      {% endfor %}
    </ul>
    </section>
  {% endif %}

  {% for sku in product.skus.all %}
    {% if forloop.first %}
      <section class="list">
        <h3>SKUs</h3>
        <table>
          <thead><tr><th>Product</th><th></th></tr></thead>
          <tbody>
    {% endif %}
          <tr>
            <td><a href="{{ sku.get_absolute_url }}">
              {{ sku.attributes_description }}
            </a></td>
            <td><a href="{{ sku.get_absolute_url }}">{{ sku.sku }}</a></td>
          </tr>
    {% if forloop.last %}
        </tbody></table>
      </section>
    {% endif %}
  {% endfor %}

  <section>
    <ul>
      <li>
        <a href="{% url "catalogue:product_list" %}" class="back">
          &larr; All products</a>
      </li>
    </ul>
  </section>

</section></section>

{% endblock %}

thecut/catalogue/templates/catalogue/sku_detail.html
{% extends "catalogue/base.html" %}

{% block title %}{{ sku.product.title }} - {{ block.super }}{% endblock %}

{% block content %}
  <header>
    <h1>{{ sku.product.title }}</h1>
{% block top_actions %}{% endblock %}
  </header>
  <section class="main-content">
  <section class="content">
    <section class="list">
      <table>
        <tbody>
        {% for skuattribute in sku.skuattributes.all %}
          <tr>
          <td>{{ skuattribute.attribute }}</td>
          <td>{{ skuattribute.value }}</td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </section>

    <ul class="actions">
      <li>
        <a href="{% url "catalogue:sku_list" %}" class="back">
          &larr; Back to all SKUs list
        </a>
      </li>
    </ul>
  </section>
  </section>

{% endblock %}

thecut/catalogue/templates/catalogue/sku_list.html
{# Is used to render list of all skus. #}
{# Has above_list_actions block to insert "Add sku" button. #}

{% extends "catalogue/base.html" %}
{% load url from future %}

{% block title %}SKUs - {{ block.super }}{% endblock %}

{% block extrahead %}
  {{ block.super }}
  {% if page_obj.paginator.num_pages > 1 %}
    {% if page_obj.has_previous %}
      {% if page_obj.previous_page_number == 1 %}
        <link rel="prev"
              href="{% url "catalogue:sku_list" %}" />
      {% else %}
        <link rel="prev"
              href="{% url "catalogue:paginated_sku_list" page=page_obj.previous_page_number %}" />
      {% endif %}
    {% endif %}
    {% if page_obj.has_next %}
      <link rel="next"
            href="{% url "catalogue:paginated_sku_list" page=page_obj.next_page_number %}"/>
    {% endif %}
  {% endif %}
{% endblock %}

{% block content %}
  <header><h1>SKUs</h1></header>

  <section class="main-content">
    <section class="content">
{% block above_list_actions %}{% endblock %}
      <section class="list">

        {% include "catalogue/_sku_list.html" with sku_list=sku_list %}

        {% if page_obj.paginator.num_pages > 1 %}
          <div>
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.

            {% if page_obj.has_previous %}
              {% if page_obj.previous_page_number == 1 %}
                <a href="{% url "catalogue:sku_list" %}"
              {% else %}
                <a href="{% url "catalogue:paginated_sku_list" page=page_obj.previous_page_number %}"
              {% endif %}
                   rel="previous">previous</a>
            {% endif %}

            {% if page_obj.has_next %}
              <a href="{% url "catalogue:paginated_sku_list" page=page_obj.next_page_number %}"
                 rel="next">next</a>
            {% endif %}

          </div>
        {% endif %}
      </section>
    </section>
  </section>
{% endblock %}